### ISSUE TITLE
Document how the streaming functionality is realized

### ISSUE THREAD

**Issue by beerendlauwers** [haskell-streaming/streaming-postgresql-simple#1]
I went through the code a bit, but I could only find stuff like this:

```Haskell
toByteString
    (byteString "FETCH FORWARD " <> intDec chunkSize <>
    byteString " FROM " <>
    byteString name)
```

Would it be possible to provide a README.md that explains what postgres functionality it uses to achieve streaming functionality?

**Comment by ocharles** [comment]
Hi. The [official documentation](https://hackage.haskell.org/package/streaming-postgresql-simple-0.1.0.0/docs/Database-PostgreSQL-Simple-Streaming.html) does explain this, see the comments on both `query` and `stream`:

For `query`

>  Uses PostgreSQL's single row mode to stream results directly from the socket to Haskell.

And for `stream`:

> This is implemented using a database cursor.

Is this documentation insufficient?

**Comment by beerendlauwers** [comment]
I appear to have looked over that. Thanks for pointing it out!
