### ISSUE TITLE
Migrate to haskell-streaming organisation

### ISSUE THREAD

**Issue by ivan-m** [haskell-streaming/streaming-postgresql-simple#4]
Hi Oliver,

Now that @andrewthad has created the @haskell-streaming organisation, would you consider transferring this repository to it?

**Comment by ocharles** [comment]
If @haskell-streaming/@andrewthad want it, but I thought it was perhaps a bit "fringe". I'm more than happy to move it though if people think it's an appropriate place for this code to live.

**Comment by andrewthad** [comment]
I would be willing to have it moved. In my mind, the organization is not a way to indicate that certain packages are blessed. For example, streaming-bytestring is much more first class than anything else (other than streaming itself). The main purpose of the organization is to help with package visibility and eliminate the single point of failure that can happen when a maintainer becomes unresponsive. (Currently, David and I are both admins in the organization).

So, yes, I would be happy to have it there.

**Comment by ocharles** [comment]
Ok, I believe to do that I need to be an admin, or at least the ability to create repositories. Transferring just now failed with "You don’t have the permission to create repositories on haskell-streaming"

**Comment by ocharles** [comment]
Done!
