### ISSUE TITLE
Feature request: API which tells you upfront how many rows will be streamed

### ISSUE THREAD

**Issue by hvr** [haskell-streaming/streaming-postgresql-simple#5]
As discussed on IRC, it appears that the low-level API (for single-row-mode as well as cursors) allows to figure out the number of rows available in a result.

One use-case where this is useful to know is for constructing e.g. (unboxed) vectors, where it's very desirable to know this information up-front, before the rows are streamed to allow for minimal-overhead construction of such vectors.

**Comment by ocharles** [comment]
Unfortunately, on closer inspection this isn't possible. In single-row mode, you repeatedly call `PQgetResult` to get a single tuple as a `Result` value. The only way to get a row count is to call `PQntuples` on a `Result`. But we know our `Result` only has one row, so this is somewhat useless for what you want.

I think you're going to have to add count information directly to your queries.

`SELECT *, count(*) over () FROM q` should work as a general wrapper.

If you think I'm wrong and this is possible, I'd love to hear how!

**Comment by hvr** [comment]
ok, but using something like `SELECT *, count(*) over () FROM q` would add marshalling overhead; i.e. if you have 1 million result rows, you'd end up having to parse the `count(*)`-integer 1 million times? (it's not a deal-breaker though)

**Comment by ocharles** [comment]
Yes, but as to whether that actually incurs a significant performance
penalty would be interesting to see.
